export const animal = [
  "aye-aye",
  "blue whale",
  "clouded leopard",
  "elephant seal",
  "emperor penguin",
  "fire salamander",
  "flying fish",
  "giraffe calf",
  "horse mackerel",
  "hummingbird hawk",
  "land crab",
  "leopard cat",
  "leopard gecko",
  "lion sea lion",
  "macaw parrot",
  "malayan tapir",
  "marsh harrier",
  "marsupial mouse",
  "neon tetra",
  "newtling frog",
  "ocean sunfish",
  "okra crab",
  "olympic trout",
  "orang fish",
  "osprey hawk",
  "osprey fish",
  "painted turtle",
  "pangapaprika",
  "parrot fish",
  "pelican fish",
  "pen shell",
  "penguin fish",
  "pheasant fish",
  "polar bear",
  "praying mantis",
  "ptarmigan bird",
  "purple martin",
  "crow",
  "grey wolf",
  "red panda",
  "axolotl",
  "harpy eagle",
  "snow leopard",
  "siberian tiger",
  "komodo dragon",
  "maned wolf",
  "proboscis monkey",
  "golden snub-nosed monkey",
  "platypus",
  "okapi",
  "tasmanian devil",
  "binturong",
  "capybara",
  "wombat",
  "aardvark",
  "sifaka lemur",
  "quokka",
  "pangolin",
  "caracal",
  "fennec fox",
  "shoebill stork",
  "tarsier",
  "harlequin frog",
  "glass frog",
  "axolotl salamander",
  "mantis shrimp",
  "electric eel",
  "blue-ringed octopus",
  "giant clam",
  "king penguin",
  "rockhopper penguin",
  "leatherback turtle",
  "green sea turtle",
  "hawksbill turtle",
  "diamondback rattlesnake",
  "king cobra",
  "goliath beetle",
  "staghorn coral",
  "sea otter",
  "river otter",
  "musk ox",
  "saola",
  "markhor",
  "nilgiri tahr",
  "ibex",
  "chameleon",
  "gecko",
  "boa constrictor",
  "anaconda",
  "arapaima",
  "coelacanth",
  "frilled shark",
  "goblin shark",
  "leaf-tailed gecko",
  "slow loris",
  "colugo",
  "pangasius catfish",
  "arctic fox",
  "snowshoe hare",
  "ermine",
  "wolverine",
  "kakapo",
  "hoatzin",
  "shoebill",
  "lyrebird",
  "cock-of-the-rock",
  "resplendent quetzal",
  "blue poison dart frog",
  "golden poison frog",
  "mantled guereza",
  "black-and-white ruffed lemur",
  "african elephant",
  "indian elephant",
  "bengal tiger",
  "malayan tiger",
  "african lion",
  "asiatic lion",
  "cheetah",
  "jaguar",
  "puma",
  "ocelot",
  "serval",
  "caracal lynx",
  "snowy owl",
  "barn owl",
  "great horned owl",
  "spotted eagle owl",
  "kestrel",
  "peregrine falcon",
  "gyrfalcon",
  "bald eagle",
  "golden eagle",
  "harlequin duck",
  "mandarin duck",
  "wood duck",
  "mallard",
  "redhead duck",
  "common loon",
  "arctic tern",
  "tern chick",
  "kingfisher",
  "bee-eater",
  "roller bird",
  "sunbird",
  "hummingbird",
  "ruby-throated hummingbird",
  "rufous hummingbird",
  "indigo bunting",
  "blue jay",
  "magpie",
  "common raven",
  "american crow",
  "jackdaw",
  "robin",
  "nightingale",
  "thrush",
  "wren",
  "blackbird",
  "starlings",
  "sparrow",
  "house sparrow",
  "tree sparrow",
  "finch",
  "goldfinch",
  "canary",
  "siskin",
  "chaffinch",
  "greenfinch",
  "bullfinch",
  "waxwing",
  "titmouse",
  "great tit",
  "blue tit",
  "coal tit",
  "crested tit",
  "long-tailed tit",
  "nuthatch",
  "treecreeper",
  "wagtail",
  "pipit",
  "lark",
  "skylark",
  "meadow pipit",
  "golden oriole",
  "black-headed oriole",
  "oriole chick",
  "shrike",
  "red-backed shrike",
  "loggerhead shrike",
  "magpie-lark",
  "fantail",
  "willow tit",
  "marsh tit",
  "coal tit",
  "crested lark",
  "hornbill",
  "toucan",
  "motmot",
  "king vulture",
  "griffon vulture",
  "lammergeier",
  "bearded vulture",
  "turkey vulture",
  "black vulture",
  "condor",
  "california condor",
  "andes condor",
  "albatross",
  "wandering albatross",
  "black-browed albatross",
  "yellow-nosed albatross",
  "petrel",
  "shearwater",
  "storm petrel",
  "penguin chick",
  "adelie penguin",
  "chinstrap penguin",
  "gentoo penguin",
  "king penguin",
  "emperor penguin",
  "little penguin",
  "fairy penguin",
  "rockhopper penguin",
  "macaroni penguin",
  "snares penguin",
  "fiordland penguin",
  "yellow-eyed penguin",
  "african penguin",
  "magellanic penguin",
  "galapagos penguin",
  "spheniscus penguin",
  "spheniscidae",
];

export const food = [
  "sweet potato",
  "mushroom mix",
  "ice cream",
  "brownie squares",
  "banana bread",
  "zucchini bread",
  "pumpkin pie",
  "apple pie",
  "peach cobbler",
  "berry crumble",
  "coconut cake",
  "cottage cheese",
  "cream cheese",
  "fettuccine alfredo",
  "chicken sandwich",
  "club sandwich",
  "burrito bowl",
  "poke bowl",
  "ramen bowl",
  "gnocchi pasta",
  "spring roll",
  "egg roll",
  "tofu teriyaki",
  "teriyaki chicken",
  "teriyaki tofu",
  "fried rice",
  "lo mein",
  "chow mein",
  "pad thai",
  "green curry",
  "red curry",
  "yellow curry",
  "massaman curry",
  "panang curry",
  "tom yum",
  "tom kha",
  "pho bo",
  "bun bo hue",
  "sticky rice",
  "sticky rice mango",
  "mango sticky rice",
  "mochi ice cream",
  "spring roll fresh",
  "spring roll fried",
  "bagel with cream cheese",
  "quesadilla wrap",
  "tortilla chips",
  "lentil curry",
  "chickpea curry",
  "spinach curry",
  "miso soup",
  "udon soup",
  "ramen soup",
  "fruit leather",
  "chex mix",
  "granola bar",
  "energy bar",
  "protein bar",
  "pita chips",
  "seaweed snack",
  "rice cracker",
  "wasabi peas",
  "edamame snack",
  "pretzel rods",
  "trail mix",
  "sunflower seeds",
  "pumpkin seeds",
  "chia seeds",
  "flax seeds",
  "hemp seeds",
  "sesame seeds",
  "rice cakes",
  "waffle cone",
  "ice cream sandwich",
  "gelato popsicle",
  "smoothie bowl",
  "acai bowl",
  "overnight oats",
  "granola parfait",
  "hot chocolate",
  "smoothie shake",
  "almond milk",
  "soy milk",
  "oat milk",
  "rice milk",
  "cashew milk",
  "coconut milk",
  "hazelnut milk",
  "taco",
];

export const game = [
  "tic tac toe",
  "connect four",
  "trivial pursuit",
  "animal crossing",
  "fall guys",
  "super smash bros",
  "pokemon legends arceus",
  "the binding of isaac",
  "enter the gungeon",
  "terraria",
  "factorio",
  "among us",
  "ark survival evolved",
  "no mans sky",
  "horizon forbidden west",
  "zelda breath of the wild",
  "mario odyssey",
  "yoshi's crafted world",
  "league of legends",
  "teamfight tactics",
  "fortnite",
  "roblox tower of hell",
  "roblox bee swarm simulator",
  "roblox adopt me",
  "slither.io",
  "agar.io",
  "rollercoaster tycoon",
  "the sims",
  "minecraft",
  "subnautica",
  "rimworld",
  "total war warhammer",
  "civilization revolution",
  "settlers 7",
  "elder scrolls legends",
  "slay the spire",
  "fable anniversary",
  "kingdom hearts",
  "bloodstained ritual of the night",
  "castlevania symphony of the night",
  "darkest dungeon",
  "toontown online",
  "pirates of the caribbean online",
  "hollow knight",
  "celeste",
  "undertale",
  "satisfactory",
  "valheim",
  "hades",
  "dead cells",
  "stardew valley",
  "oxygen not included",
  "dont starve",
  "the forest",
  "green hell",
  "7 days to die",
  "vampire survivors",
  "loop hero",
  "monster hunter rise",
  "elden ring",
  "dark souls",
  "bloodborne",
  "sekiro shadows die twice",
  "ghost of tsushima",
  "god of war",
  "spider-man ps4",
  "batman arkham asylum",
  "witcher 3 wild hunt",
  "cyberpunk 2077",
  "final fantasy vii remake",
  "persona 5",
  "fire emblem three houses",
  "xenoblade chronicles",
  "metroid dread",
  "super mario galaxy",
  "luigi's mansion",
  "pikmin",
  "donkey kong country tropical freeze",
  "mario kart 8 deluxe",
  "mortal kombat 11",
  "street fighter v",
  "tekken 7",
  "splatoon 2",
  "overwatch",
  "apex legends",
  "valorant",
  "dota 2",
  "hearthstone",
  "starcraft 2",
  "diablo 3",
  "path of exile",
  "world of warcraft",
  "final fantasy xiv",
  "into the breach",
  "katana zero",
  "hyper light drifter",
  "dead by daylight",
  "hunt showdown",
  "escape from tarkov",
  "rust",
  "journey",
  "limbo",
  "inside",
  "little nightmares",
  "katamari damacy",
  "psychonauts",
  "bastion",
  "transistor",
  "pyre",
  "child of light",
  "superliminal",
  "the witness",
  "manifold garden",
  "obduction",
  "myst",
  "riven",
  "the talos principle",
  "antichamber",
  "portal",
  "the swapper",
  "fez",
  "oxenfree",
  "firewatch",
  "what remains of edith finch",
  "gone home",
  "the stanley parable",
  "the artful escape",
  "gris",
  "a short hike",
  "tunic",
  "crypt of the necroDancer",
];

export const place = [
  "school",
  "beach",
  "park",
  "mall",
  "library",
  "museum",
  "city",
  "forest",
  "island",
  "mountain",
  "airport",
  "stadium",
  "desert",
  "village",
  "bridge",
  "castle",
  "garden",
  "cave",
  "harbor",
  "jungle",
  "house",
  "farm",
  "zoo",
  "factory",
  "restaurant",
  "hospital",
  "bank",
  "hotel",
  "theater",
  "station",
  "market",
  "church",
  "mosque",
  "temple",
  "synagogue",
  "arena",
  "square",
  "playground",
  "highway",
  "road",
  "street",
  "alley",
  "court",
  "plaza",
  "pier",
  "bay",
  "valley",
  "river",
  "lake",
  "ocean",
  "pond",
  "beachfront",
  "cliff",
  "canyon",
  "hill",
  "plateau",
  "volcano",
  "glacier",
  "swamp",
  "marsh",
  "mine",
  "quarry",
  "hut",
  "lighthouse",
  "tower",
  "amusement park",
  "waterpark",
  "school bus stop",
  "bus terminal",
  "train yard",
  "subway tunnel",
  "pier shop",
  "boardwalk",
  "ski resort",
  "snowfield",
  "observatory",
  "planetarium",
  "laboratory",
  "university",
  "dormitory",
  "cafeteria",
  "bakery",
  "butcher shop",
  "pharmacy",
  "barbershop",
  "salon",
  "spa",
  "gym",
  "skatepark",
  "basketball court",
  "tennis court",
  "golf course",
  "race track",
  "railroad crossing",
  "truck stop",
  "gas station",
  "car dealership",
  "car wash",
  "parking garage",
  "parking lot",
  "warehouse",
  "power plant",
  "water treatment plant",
  "wind farm",
  "solar farm",
  "construction site",
  "junkyard",
  "dockyard",
  "shipyard",
  "airport runway",
  "helipad",
  "train bridge",
  "waterfall",
  "geyser",
  "lagoon",
  "reef",
  "deep forest",
  "savanna",
  "tundra",
  "arctic station",
  "igloo",
  "oasis",
  "monument",
  "memorial",
  "cemetery",
  "crypt",
  "ruins",
  "old temple",
  "underground bunker",
  "military base",
  "barracks",
  "border checkpoint",
  "embassy",
  "city hall",
  "courthouse",
  "police station",
  "fire station",
  "post office",
  "news station",
  "radio station",
  "tv studio",
  "recording studio",
  "art studio",
  "photo studio",
  "greenhouse",
  "arboretum",
  "orchard",
  "vineyard",
  "ranch",
  "stable",
  "kennel",
  "aquarium",
  "aviary",
  "terrarium",
  "underground cave",
  "basement",
  "attic",
  "rooftop",
  "penthouse",
  "courtyard",
  "town square",
  "food truck park",
  "farmer market",
  "night market",
  "flea market",
  "bazaar",
  "caravan camp",
  "tent camp",
  "military checkpoint",
  "observation deck",
  "tram station",
  "skybridge",
  "business district",
  "industrial zone",
  "residential area",
  "suburbs",
  "slum",
  "shantytown",
  "dock",
  "boathouse",
  "fishing village",
  "shipwreck",
  "underwater ruins",
  "coral atoll",
  "hot spring",
  "steam vent",
  "crater",
  "meteor site",
  "summit",
  "ridge",
  "outpost",
  "watchtower",
  "fort",
  "stronghold",
  "keep",
  "bunker",
  "labyrinth",
  "tunnel",
  "mineshaft",
  "train tunnel",
  "sewer",
  "underground city",
  "underground market",
];

export const object = [
  "phone",
  "laptop",
  "chair",
  "table",
  "pencil",
  "backpack",
  "bottle",
  "car",
  "ball",
  "mirror",
  "keyboard",
  "clock",
  "helmet",
  "candle",
  "camera",
  "remote",
  "glasses",
  "wallet",
  "shovel",
  "blanket",
  "toaster",
  "charger",
  "radio",
  "broom",
  "brush",
  "flashlight",
  "marker",
  "stapler",
  "headphones",
  "controller",
  "notebook",
  "book",
  "paper",
  "eraser",
  "pen",
  "ruler",
  "scissors",
  "printer",
  "monitor",
  "lamp",
  "microwave",
  "oven",
  "fan",
  "sofa",
  "couch",
  "bed",
  "mat",
  "tent",
  "umbrella",
  "boots",
  "shoe",
  "hat",
  "coat",
  "jacket",
  "bag",
  "stool",
  "bin",
  "bucket",
  "mug",
  "plate",
  "fork",
  "spoon",
  "knife",
  "cup",
  "jar",
  "tray",
  "globe",
  "map",
  "calendar",
  "thermometer",
  "compass",
  "telescope",
  "binoculars",
  "magnifying glass",
  "key",
  "lock",
  "chain",
  "rope",
  "string",
  "belt",
  "paint brush",
  "hammer",
  "screwdriver",
  "wrench",
  "pliers",
  "drill",
  "saw",
  "spade",
  "hoe",
  "rake",
  "tablet",
  "smartwatch",
  "earbuds",
  "power bank",
  "usb drive",
  "memory card",
  "hard drive",
  "router",
  "speaker",
  "projector",
  "microphone",
  "walkie talkie",
  "calculator",
  "whiteboard",
  "clipboard",
  "folder",
  "envelope",
  "highlighter",
  "paperclip",
  "rubber band",
  "tape",
  "glue",
  "hole puncher",
  "bookmark",
  "paint palette",
  "canvas",
  "easel",
  "sketchbook",
  "chalk",
  "crayon",
  "pastel",
  "ink bottle",
  "quill",
  "typewriter",
  "record player",
  "vinyl record",
  "cassette tape",
  "cd",
  "blu ray",
  "tripod",
  "selfie stick",
  "phone case",
  "screen protector",
  "sd card reader",
  "vr headset",
  "drone",
  "game cartridge",
  "joystick",
  "graphics tablet",
  "mouse pad",
  "extension cord",
  "power strip",
  "lightbulb",
  "lantern",
  "oil lamp",
  "camp stove",
  "camp chair",
  "sleeping bag",
  "hammock",
  "cooler",
  "canteen",
  "canteen cup",
  "thermos",
  "kettle",
  "frying pan",
  "saucepan",
  "skillet",
  "baking sheet",
  "mixing bowl",
  "cutting board",
  "whisk",
  "spatula",
  "ladle",
  "tongs",
  "peeler",
  "grater",
  "colander",
  "measuring cup",
  "measuring spoon",
  "rolling pin",
  "mortar",
  "pestle",
  "blender",
  "food processor",
  "rice cooker",
  "toaster oven",
  "air fryer",
  "pressure cooker",
  "slow cooker",
  "water filter",
  "dish rack",
  "napkin",
  "tablecloth",
  "coaster",
  "serving spoon",
  "oven mitt",
  "apron",
  "laundry basket",
  "iron",
  "ironing board",
  "vacuum",
  "mop",
  "dustpan",
  "feather duster",
  "spray bottle",
  "detergent",
  "sponge",
  "scrub brush",
  "toolbox",
  "level",
  "utility knife",
  "crowbar",
  "tape measure",
  "hex key",
  "socket wrench",
  "soldering iron",
  "welding mask",
  "ladder",
  "step stool",
  "wheelbarrow",
  "garden hose",
  "watering can",
  "fertilizer bag",
  "seed packet",
  "garden shears",
  "pruning saw",
  "trowel",
  "snow shovel",
  "ice scraper",
  "fire extinguisher",
  "first aid kit",
  "bandage",
  "thermoscanner",
  "stethoscope",
  "syringe",
  "pill bottle",
  "crutch",
  "wheelchair",
  "thermometer strip",
  "blood pressure monitor",
  "yoga mat",
  "dumbbell",
  "barbell",
  "kettlebell",
  "jump rope",
  "punching bag",
  "exercise ball",
  "foam roller",
  "resistance band",
  "helmet light",
  "ski mask",
  "goggles",
  "life jacket",
  "parachute",
  "compass watch",
  "mailbox",
  "door handle",
  "keycard",
  "badge",
  "ID card",
  "passport",
  "ticket",
  "wallet chain",
  "coin",
  "piggy bank",
  "credit card",
  "dice",
  "card deck",
  "chess set",
  "board game",
  "puzzle",
  "toy car",
  "lego brick",
  "action figure",
  "doll",
  "teddy bear",
  "yo yo",
  "frisbee",
  "skateboard",
  "scooter",
  "roller skates",
  "sled",
  "bicycle",
  "helmet strap",
  "water bottle holder",
  "guitar",
  "violin",
  "piano",
  "flute",
  "drum",
  "trumpet",
  "saxophone",
  "harmonica",
  "ukulele",
  "micro sd adapter",
  "electric cable",
  "wire cutter",
  "battery",
  "AA battery",
  "AAA battery",
  "car battery",
  "light switch",
  "doorbell",
  "thermostat",
  "smoke detector",
  "carbon monoxide detector",
];

export const sport = [
  "soccer",
  "basketball",
  "baseball",
  "football",
  "tennis",
  "golf",
  "swimming",
  "boxing",
  "hockey",
  "volleyball",
  "track",
  "wrestling",
  "rugby",
  "cycling",
  "skiing",
  "snowboarding",
  "karate",
  "bowling",
  "archery",
  "fencing",
  "rowing",
  "gymnastics",
  "skateboarding",
  "surfing",
  "badminton",
  "cricket",
  "handball",
  "judo",
  "lacrosse",
  "martial arts",
  "polo",
  "softball",
  "table tennis",
  "taekwondo",
  "triathlon",
  "weightlifting",
  "yoga",
  "kickboxing",
  "sailing",
  "diving",
  "climbing",
  "snowboarding",
  "sledding",
  "ice hockey",
  "figure skating",
  "speed skating",
  "kayaking",
  "canoeing",
  "surfing",
  "windsurfing",
  "paragliding",
  "bmx",
  "rollerblading",
  "motocross",
  "paintball",
  "laser tag",
  "archery tag",
  "parkour",
  "skating",
  "crossfit",
  "pilates",
  "fencing",
  "squash",
  "racquetball",
  "track and field",
  "rugby union",
  "rugby eight",
  "american football",
  "soccer futsal",
  "handball beach",
  "volleyball beach",
  "softball fastpitch",
  "floorball",
  "ice climbing",
  "mountain biking",
  "orienteering",
  "triathlon sprint",
  "swimrun",
  "ultramarathon",
  "trail running",
];

export const movies = [
  "the last emperor",
  "crash",
  "american beauty",
  "the usual suspects",
  "a history of violence",
  "the wrestler",
  "the big chill",
  "lost in translation",
  "the crying game",
  "the reader",
  "babel",
  "the mission",
  "the english patient",
  "there will be blood",
  "the master",
  "phantom thread",
  "boogie nights",
  "magnolia",
  "cape fear",
  "the aviator",
  "casino",
  "goodfellas",
  "raging bull",
  "the king of comedy",
  "frailty",
  "the assassination of jesse james",
  "just friends",
  "the fall",
  "the fountain",
  "ceremony",
  "21 grams",
  "the hours",
  "the pianist",
  "black book",
  "the lives of others",
  "a prophet",
  "run lola run",
  "man on fire",
  "the bone collector",
  "inside man",
  "the negotiator",
  "enemy of the state",
  "the game",
  "the score",
  "ronin",
  "the fugitive",
  "eraser",
  "heatwave",
  "eye in the sky",
  "the king’s man",
  "hawk the slayer",
  "the machinist",
  "the mechanic",
  "michael clayton",
  "22 july",
  "the grey",
  "mystic river",
  "at close range",
  "blow",
  "being john malkovich",
  "eternity and a day",
  "trainspotting",
  "the full monty",
  "the commitments",
  "lock stock and two smoking barrels",
  "snatch",
  "layer cake",
  "the gentleman",
  "the rock",
  "con air",
  "face off",
  "lord of war",
  "next",
  "national treasure",
  "weathering with you",
  "the secret world of arrietty",
  "porco rosso",
  "howl’s moving castle",
  "whisper of the heart",
  "the wind rises",
  "grave of the fireflies",
  "your name",
  "wolf children",
  "a silent voice",
  "perfect blue",
  "paprika",
  "the girl who leapt through time",
  "millennium actress",
  "akira",
  "ninja scroll",
  "the raid",
  "the raid redemption",
  "oldboy",
  "memories of murder",
  "parasite",
  "okja",
  "snowpiercer",
  "burning",
  "the handmaiden",
  "train to busan",
  "a taxi driver",
  "the wailing",
  "the chaser",
  "the host",
  "shoplifters",
  "rashomon",
  "seven samurai",
  "ronin",
  "throne of blood",
  "ran",
  "ikiru",
  "y tu mamá también",
  "amores perros",
  "roma",
  "city of god",
  "central station",
  "elite squad",
  "forrest gump",
  "cast away",
  "road to perdition",
  "doubt",
  "the visitor",
  "the station agent",
  "blue ruin",
  "hellboy",
  "constantine",
  "chronicle",
  "bright",
  "limitless",
  "lucy",
  "the adjustment bureau",
  "the conjuring",
  "insidious",
  "sinister",
  "the babadook",
  "the others",
  "the orphan",
  "mama",
  "lights out",
  "it follows",
  "drag me to hell",
  "the descent",
  "pandorum",
  "sunshine",
  "moon",
  "annihilation",
  "oblivion",
  "the knowing",
  "coherence",
  "the signal",
  "predestination",
  "triangle",
  "the endless",
  "underwater",
  "the thing",
  "the fly",
  "the fog",
  "poltergeist",
  "the omen",
  "the orphanage",
  "raw",
  "martyrs",
  "antichrist",
  "the skin i live in",
  "the invisible guest",
  "the platform",
  "the sea inside",
  "open your eyes",
  "biutiful",
  "spring breakers",
  "drive",
  "wild at heart",
  "blue velvet",
  "mulholland drive",
  "eraserhead",
  "twin peaks fire walk with me",
  "a ghost story",
  "american honey",
  "snow angels",
  "the tree of life",
  "the new world",
  "the thin red line",
  "days of heaven",
  "stand by me",
  "the outsiders",
  "the sandlot",
  "big fish",
  "edward scissorhands",
  "beetlejuice",
  "the nightmare before christmas",
  "coraline",
  "the witch",
  "the northman",
  "the rover",
  "the proposition",
  "three kings",
  "the hurt locker",
  "jarhead",
  "black hawk down",
  "13 hours",
  "patriots day",
  "the report",
  "spotlight",
  "the post",
  "sully",
  "all is lost",
  "gravity",
  "source code",
  "the number 23",
  "phone booth",
  "28 days later",
  "sunshine cleaning",
  "mystery men",
  "the switch",
  "stardust",
  "secondhand lions",
  "the secret garden",
  "bridge to terabithia",
  "the golden compass",
  "inkheart",
  "miss peregrine's home for peculiar children",
  "big miracle",
  "hidden life",
  "little miss sunshine",
  "the peanut butter falcon",
  "the florida project",
  "the squid and the whale",
  "mid90s",
  "whale rider",
  "the rider",
  "coda",
  "the farewell",
  "the lost daughter",
  "locke",
  "24 hour party people",
  "the world’s end",
  "attack the block",
  "paul",
  "hot rod",
  "the nice guys",
  "tropic thunder",
  "the big sick",
  "the interview",
  "the dictator",
  "zombieland",
  "warm bodies",
  "the fundamental elements of crime",
  "the ides of march",
  "margaret",
  "monsters",
  "the beach",
  "the talented mr ripley",
  "snake eyes",
  "mystery alaska",
  "rounders",
  "the negotiator",
  "runaway jury",
  "the lincoln lawyer",
  "fracture",
  "secret window",
  "matchstick men",
  "the firm",
  "the pelican brief",
  "a time to kill",
  "the hurricane",
  "dead man",
  "the proposition",
  "moonlight mile",
  "the station agent",
  "the visitor",
  "the spectacular now",
  "patriot games",
  "clear and present danger",
];

export const body = [
  "head",
  "arm",
  "leg",
  "hand",
  "foot",
  "eye",
  "ear",
  "nose",
  "mouth",
  "neck",
  "shoulder",
  "chest",
  "back",
  "stomach",
  "knee",
  "elbow",
  "wrist",
  "ankle",
  "finger",
  "toe",
  "hair",
  "brain",
  "heart",
  "lung",
  "liver",
  "kidney",
  "teeth",
  "tongue",
  "skin",
  "spine",
  "rib",
  "pelvis",
  "thigh",
  "calf",
  "heel",
  "forearm",
  "eyebrow",
  "eyelash",
  "cheek",
  "chin",
  "jaw",
  "shoulder blade",
  "collarbone",
  "palm",
  "fingernail",
  "toenail",
  "thumb",
  "index finger",
  "middle finger",
  "ring finger",
  "pinky",
  "abdomen",
  "waist",
  "hip",
  "buttock",
  "groin",
  "hamstring",
  "shin",
  "sole",
  "arch",
  "temple",
  "crown",
  "scalp",
  "forehead",
  "nostril",
  "lip",
  "gum",
  "uvula",
  "throat",
  "larynx",
  "trachea",
  "shoulder joint",
  "kneecap",
  "achilles",
  "upper arm",
  "lower leg",
  "spine base",
  "vertebra",
  "sternum",
  "abdomen upper",
  "abdomen lower",
  "side",
  "flank",
  "nape",
  "knuckle",
  "cuticle",
  "bridge of nose",
  "jawline",
  "earlobe",
  "iris",
  "pupil",
  "retina",
  "bronchus",
  "diaphragm",
  "intestine",
  "appendix",
  "spleen",
  "pancreas",
  "cartilage",
  "ligament",
  "tendon",
  "hypothalamus",
  "pituitary",
  "cerebellum",
  "medulla",
  "esophagus",
  "duodenum",
  "colon",
  "rectum",
  "gallbladder",
  "aorta",
  "vena cava",
  "artery",
  "vein",
  "capillary",
  "lymph node",
  "lymph vessel",
  "bronchiole",
  "alveoli",
  "muscle fiber",
  "fascia",
  "joint capsule",
  "cartilage plate",
  "tibia",
  "fibula",
  "humerus",
  "radius",
  "ulna",
  "femur",
  "scapula",
  "clavicle",
  "mandible",
  "maxilla",
  "occiput",
  "temporal bone",
  "parietal bone",
  "frontal bone",
  "orbital cavity",
  "sinus",
  "soft palate",
  "hard palate",
  "pharynx",
  "epiglottis",
  "windpipe",
  "sternocleidomastoid",
  "trapezius",
  "deltoid",
  "bicep",
  "tricep",
  "quadricep",
  "gastroc",
  "soleus",
  "latissimus",
  "oblique",
  "abductor",
  "adductor",
  "flexor",
  "extensor",
  "metacarpal",
  "metatarsal",
  "heel pad",
  "knee pit",
  "wing scapula",
  "upper back",
  "mid back",
  "lower back",
  "lumbar region",
  "sacrum",
  "coccyx",
  "eye corner",
  "tear duct",
  "cheekbone",
  "nasal bridge",
  "laryngeal cartilage",
  "voice box",
  "shoulder tip",
  "elbow point",
  "ankle bone",
  "heel bone",
  "instep",
  "ball of the foot",
  "fingertip",
  "toe tip",
];

export const health = [
  "exercise",
  "diet",
  "sleep",
  "hydration",
  "vitamin",
  "protein",
  "minerals",
  "cardio",
  "strength",
  "stretching",
  "yoga",
  "meditation",
  "mental health",
  "stress",
  "wellbeing",
  "nutrition",
  "balance",
  "immunity",
  "relaxation",
  "hygiene",
  "doctor",
  "checkup",
  "vaccine",
  "workout",
  "endurance",
  "flexibility",
  "calories",
  "metabolism",
  "cholesterol",
  "blood pressure",
  "heart health",
  "mindfulness",
  "recovery",
  "supplement",
  "prevention",
  "therapy",
  "rehabilitation",
  "walking",
  "running",
  "swimming",
  "cycling",
  "rest",
  "hydrated",
  "healthy",
  "organic",
  "whole foods",
  "aerobics",
  "strength training",
  "mobility",
  "posture",
  "core training",
  "breathing exercises",
  "wellness",
  "self care",
  "body balance",
  "joint health",
  "muscle health",
  "cardiovascular health",
  "immune health",
  "gut health",
  "digestive health",
  "fitness",
  "bodyweight training",
  "pilates",
  "tai chi",
  "outdoor activity",
  "sports",
  "interval training",
  "HIIT",
  "low impact",
  "high impact",
  "aerobic capacity",
  "stamina",
  "hydration levels",
  "electrolytes",
  "antioxidants",
  "fiber",
  "healthy habits",
  "lifestyle",
  "healthy living",
  "meal planning",
  "portion control",
  "balanced meals",
  "fresh foods",
  "plant based",
  "lean protein",
  "nutrient density",
  "whole grains",
  "hearty routine",
  "health check",
  "annual exam",
  "screening",
  "wellness visit",
  "self assessment",
  "relaxation techniques",
  "deep breathing",
  "mind body connection",
  "positivity",
  "emotional health",
  "resilience",
  "self esteem",
  "focus",
  "clarity",
  "productivity",
  "burnout prevention",
  "energy management",
  "mobility training",
  "functional fitness",
  "daily activity",
  "movement",
  "step count",
  "active habit",
  "healthy weight",
  "body composition",
  "heart strength",
  "lung capacity",
  "circulation",
  "blood flow",
  "hydration habit",
  "wellness routine",
  "good nutrition",
  "mindful movement",
  "sleep quality",
  "restoration",
  "rest and recovery",
  "energy levels",
  "body care",
  "clean eating",
  "natural foods",
  "healthy choices",
  "health goals",
  "wellbeing goals",
  "daily wellness",
  "healthy focus",
  "strength endurance",
  "mental clarity",
  "relaxing activities",
  "stress relief",
  "positive habits",
  "body awareness",
  "holistic health",
  "active wellness",
  "health maintenance",
  "preventative steps",
  "fitness routine",
  "active lifestyle",
  "calorie balance",
  "hydration goal",
  "exercise habit",
  "clean lifestyle",
  "mind health",
  "wellness habits",
  "health support",
  "health tracking",
];

export const music = [
  "Bohemian Rhapsody",
  "Hotel California",
  "Blinding Lights",
  "Smells Like Teen Spirit",
  "Shape of You",
  "Billie Jean",
  "Clocks",
  "Lose Yourself",
  "Viva La Vida",
  "Hallelujah",
  "Wonderwall",
  "Imagine",
  "Thriller",
  "Rolling in the Deep",
  "Purple Rain",
  "Take On Me",
  "Hey Jude",
  "Uptown Funk",
  "Stairway to Heaven",
  "Back in Black",
  "Chandelier",
  "Numb",
  "Shake It Off",
  "Counting Stars",
  "Somebody That I Used to Know",
  "Radioactive",
  "Believer",
  "Can't Stop the Feeling!",
  "Smooth Criminal",
  "Dream On",
  "Seven Nation Army",
  "Bad Guy",
  "Lose Control",
  "In the End",
  "Thunderstruck",
  "Mr. Brightside",
  "All of Me",
  "Levitating",
  "Skyfall",
  "Toxic",
  "Firework",
  "Take Me to Church",
  "Vivid Dreams",
  "Sunflower",
  "Old Town Road",
  "Good 4 U",
  "Drivers License",
  "Stay",
  "Heat Waves",
  "Peaches",
  "Can't Feel My Face",
  "Shake It",
  "Memories",
  "Don't Stop Believin'",
  "Africa",
  "I Will Survive",
  "Superstition",
  "Sweet Child O' Mine",
  "Livin' on a Prayer",
  "Poker Face",
  "Bad Romance",
  "Stronger",
  "Strangers",
  "Dancing Queen",
  "Boulevard of Broken Dreams",
  "Zombie",
  "Paint It Black",
  "Eye of the Tiger",
  "Another One Bites the Dust",
  "Beat It",
  "Empire State of Mind",
  "Shallow",
  "Happy",
  "Royals",
  "Grenade",
  "Locked Out of Heaven",
  "Can't Hold Us",
  "Demons",
  "Let Her Go",
  "Riptide",
  "All Star",
  "Paradise",
  "No Tears Left to Cry",
  "Without Me",
  "Rockstar",
  "Circles",
  "Happier",
  "Elastic Heart",
  "Lovely",
  "Cheap Thrills",
  "Faded",
  "Stitches",
  "Ride",
  "Heathens",
  "HUMBLE.",
  "God's Plan",
  "Sicko Mode",
  "We Will Rock You",
  "Under Pressure",
  "Time After Time",
  "Karma Police",
  "Everlong",
  "The Middle",
  "Black Hole Sun",
  "Iris",
  "Sweet Dreams (Are Made of This)",
  "Smooth",
  "Bad Habits",
  "Unholy",
  "Flowers",
  "As It Was",
  "Vampire",
  "Daylight",
  "Save Your Tears",
  "Positions",
  "The Nights",
  "Animals",
  "Maps",
  "Payphone",
  "Love Me Again",
  "Pumped Up Kicks",
  "Renegades",
  "Sweater Weather",
  "Youngblood",
  "Before You Go",
  "Say You Won't Let Go",
  "Cold Heart",
  "Feel Good Inc.",
  "Gorillaz - Clint Eastwood",
  "Mr. Blue Sky",
  "Break My Heart",
  "Running Up That Hill",
  "Electric Feel",
  "Midnight City",
  "Kids",
  "Take My Breath",
  "Die For You",
  "Smooth Operator",
  "Man in the Mirror",
  "Rhythm Nation",
  "Ghostbusters",
  "Everybody Wants to Rule the World",
  "Take It Easy",
  "More Than a Feeling",
  "Don’t You (Forget About Me)",
  "Here Comes the Sun",
  "Come Together",
  "Let It Be",
  "Blackbird",
  "Comfortably Numb",
  "Money",
  "Wish You Were Here",
  "Time (Pink Floyd)",
  "Baba O’Riley",
  "My Generation",
  "Pinball Wizard",
  "Born to Run",
  "Dancing in the Dark",
  "Thunder Road",
  "American Pie",
  "Lean On",
  "Turn Down for What",
  "Trap Queen",
  "Congratulations",
  "Lucid Dreams",
  "XO TOUR Llif3",
  "Goosebumps",
  "Mask Off",
  "Bad and Boujee",
  "Godzilla",
  "Rap God",
  "Love the Way You Lie",
  "Not Afraid",
  "Stronger (Kanye West)",
  "Heartless",
  "Flashing Lights",
  "Gold Digger",
  "Power",
  "Fix You",
  "Yellow",
  "Talk",
  "Adventure of a Lifetime",
  "Higher Power",
  "Centuries",
  "The Phoenix",
  "Immortals",
  "Thnks fr th Mmrs",
  "I Write Sins Not Tragedies",
  "The Ballad of Mona Lisa",
  "High Hopes",
  "House of the Rising Sun",
  "Bad Moon Rising",
  "Fortunate Son",
  "Proud Mary",
  "Have You Ever Seen the Rain?",
  "Sweet Home Alabama",
  "Free Bird",
  "Simple Man",
  "Johnny B. Goode",
  "Great Balls of Fire",
  "Jailhouse Rock",
  "Hound Dog",
  "Satisfaction",
  "Start Me Up",
  "Angie",
  "Heroes",
  "Life on Mars?",
  "Space Oddity",
  "Rebel Rebel",
  "Heart-Shaped Box",
  "Come As You Are",
  "Jeremy",
  "Even Flow",
  "Black",
  "Alive",
  "Californication",
  "Otherside",
  "Can't Stop",
  "By the Way",
  "Dani California",
  "Scar Tissue",
  "Dreams",
  "Go Your Own Way",
  "The Chain",
  "Rhiannon",
  "Landslide",
  "Edge of Seventeen",
  "Don’t Stop Me Now",
  "Somebody to Love",
  "Radio Ga Ga",
  "Flash",
  "We Are the Champions",
  "Take a Bow",
  "Unwritten",
  "Torn",
  "Breakeven",
  "Hall of Fame",
  "Secrets",
  "Counting Blue Cars",
  "How to Save a Life",
  "Over My Head (Cable Car)",
  "Viva Forever",
  "Say My Name",
  "Survivor",
  "No Scrubs",
  "Waterfalls",
  "Un-Break My Heart",
  "I Want It That Way",
  "Everybody (Backstreet's Back)",
  "Bye Bye Bye",
  "It's Gonna Be Me",
  "Genie in a Bottle",
  "What a Girl Wants",
  "Beautiful",
  "Fighter",
  "Hips Don't Lie",
  "Whenever, Wherever",
  "Waka Waka",
  "Call Me Maybe",
  "Fireflies",
  "Good Time",
  "Hey, Soul Sister",
  "Drive By",
  "Holiday",
  "21 Guns",
  "Wake Me Up When September Ends",
  "American Idiot",
  "She Will Be Loved",
  "Sugar",
  "Moves Like Jagger",
  "Wake Me Up",
  "Levels",
  "Waiting for Love",
  "Alone (Alan Walker)",
  "Spectrum",
  "Clarity",
  "Stay the Night",
  "Break Free",
  "No Lie",
  "One Dance",
  "Hotline Bling",
  "Passionfruit",
  "In My Feelings",
  "Nice for What",
  "Replay",
  "Dynamite",
  "Butter",
  "Idol",
  "Blood Sweat & Tears",
  "Fake Love",
  "Permission to Dance",
  "Closer",
  "Don't Let Me Down",
  "Something Just Like This",
  "Roses",
  "Paris",
  "Turn Up the Speakers",
  "Don't You Worry Child",
  "Save the World",
  "Miami 2 Ibiza",
  "Heroes (We Could Be)",
  "Cool for the Summer",
  "Confident",
  "Sorry Not Sorry",
  "7 Rings",
  "Thank U, Next",
  "Into You",
  "Side to Side",
  "Love Story",
  "You Belong with Me",
  "Blank Space",
  "All Too Well",
  "Anti-Hero",
  "Cruel Summer",
  "Cardigan",
  "August",
  "Bad Blood",
  "Look What You Made Me Do",
  "Formation",
  "Halo",
  "Single Ladies",
  "Crazy in Love",
  "Run the World (Girls)",
  "Irreplaceable",
];

export const song_lyrics = [
  "Is this the real life? Is this just fantasy?",
  "There's a lady who's sure all that glitters is gold",
  "Hello from the other side",
  "We don't need no education",
  "I stay out too late, got nothing in my brain",
  "She told me her name was Billie Jean",
  "Lights will guide you home",
  "Look, if you had one shot, or one opportunity",
  "I used to rule the world",
  "I heard there was a secret chord",
  "Today is gonna be the day that they're gonna throw it back to you",
  "Imagine all the people living life in peace",
  "It's close to midnight and something evil's lurking in the dark",
  "There's a fire starting in my heart",
  "Purple rain, purple rain",
  "Take on me, take me on",
  "Hey Jude, don't make it bad",
  "Don't believe me, just watch",
  "Clocks keep ticking, ticking",
  "I'm on the edge of glory",
  "I've become so numb, I can't feel you there",
  "Just shake it off",
  "I see it in your eyes",
  "Somebody that I used to know",
  "I'm waking up to ash and dust",
  "First things first, I'ma say all the words inside my head",
  "I can't stop this feeling",
  "Annie, are you okay?",
  "Sing with me, sing for the year",
  "In the end, it doesn't even matter",
  "Thunder, thunder, thunder",
  "Coming out of my cage and I've been doing just fine",
  "All of me loves all of you",
  "I got my ticket for the long way 'round",
  "There's a fire in the sky",
  "I'm off the deep end, watch as I dive in",
  "I want to hold your hand",
  "Dancing queen, feel the beat from the tambourine",
  "We are the champions, my friends",
  "I see trees of green, red roses too",
  "Hit me baby one more time",
  "Cause baby you're a firework",
  "You're beautiful, it's true",
  "I kissed a girl and I liked it",
  "I'm a survivor, I'm not gonna give up",
  "Don't stop believin', hold on to that feeling",
  "Africa, bless the rains down in Africa",
  "Hey, I just met you, and this is crazy",
  "I want it that way",
  "It's my life, it's now or never",
  "I got a feeling, that tonight's gonna be a good night",
  "I see a little silhouetto of a man",
  "All the single ladies, all the single ladies",
  "Just a small town girl, living in a lonely world",
  "Sweet dreams are made of this",
  "Take me to church",
  "Hello, can you hear me?",
  "Wake me up before you go-go",
  "I've paid my dues, time after time",
  "Rolling in the deep",
  "Somewhere over the rainbow",
  "I will always love you",
  "Let it be, let it be",
  "I believe I can fly",
  "Under pressure, pushing down on me",
  "Hit the road Jack, and don't you come back no more",
  "Every breath you take",
  "Nothing else matters",
  "Say my name, say my name",
  "You're in the army now",
  "With or without you",
  "Sweet child o' mine",
  "Pour some sugar on me",
  "Livin' on a prayer",
  "Summer of '69",
  "Don't you forget about me",
  "Wake me up when September ends",
  "I can't get no satisfaction",
  "I wanna dance with somebody",
  "Girls just wanna have fun",
  "Material girl",
  "Like a virgin",
  "Time after time",
  "True colors",
  "Man in the mirror",
  "Black or white",
  "Heal the world",
  "Smooth criminal",
  "Beat it",
  "Thriller night",
  "Say you won't let go",
  "Stay with me",
  "Shallow, shallow",
  "I don't wanna miss a thing",
  "Every little thing she does is magic",
  "Here comes the sun",
  "Let her go",
  "Thinking out loud",
  "Photograph",
  "Love me tender",
  "Fly me to the moon",
  "New York, New York",
  "My heart will go on",
  "You belong with me",
  "Blank space, baby",
  "We found love in a hopeless place",
  "Love on the brain",
  "Toxic, taste of your lips",
  "Since U Been Gone",
  "Complicated",
  "I'm yours, I won't give up on us",
  "Count on me",
  "Roar, roar, roar",
  "Brave, brave, brave",
  "Call me maybe",
  "Let me love you",
  "Hotline bling",
  "Sorry, not sorry",
  "Montero, call me by your name",
  "Deja vu, I see you",
  "Happier than ever, in the rain",
  "Everything I wanted",
  "Therefore I am, you can’t see me",
  "Willow, go your own way",
  "traitor, you played me",
  "positions, I’m on top",
  "34+35, counting numbers",
  "WAP, wet and wild",
  "Mood, I’m in the mood",
  "Savage, classy, bougie",
  "Rockstar, I'm living fast",
  "Life is good, feeling fine",
  "Levitating, up in the sky",
  "Heat waves, running through my heart",
  "drivers license, I got my license",
  "Good 4 u, moving on",
  "Peaches, I got my peaches",
  "As it was",
  "Anti-hero, it’s me",
  "About damn time",
  "Bad habits, creeping up",
  "Easy on me, go easy",
  "Ghost, I feel you tonight",
  "Butter, smooth like butter",
  "Dynamite, shine bright like dynamite",
  "Savage love, breaking hearts",
  "Industry baby, I got the keys",
  "Blinding lights, I’m blinded",
  "Heartless, in the night",
  "Save your tears for another day",
  "Take my breath",
  "good 4 u, feeling new",
  "Peaches, taste the sweetness",
  "Anti-hero, face yourself",
  "Easy on me, forgive me",
];

export const history = [];
