name: Deploy Frontend

on:
  push:
    branches: [main]
    paths:
      - "client/**"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Upload site
        uses: actions/upload-pages-artifact@v3
        with:
          path: client/src

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
